<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class LombaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('lomba')->insert([
            [
                'nama' => 'Hackathon Indonesia',
                'penyelenggara' => 'Kemenkominfo',
                'tingkat' => 'Nasional',
                'bidang_keahlian_id' => 4,
                'persyaratan' => 'Mahasiswa aktif',
                'jumlah_peserta' => 1,
                'link_registrasi' => 'https://HackathonIndonesia.com',
                'tanggal_mulai' => '2025-09-01',
                'tanggal_selesai' => '2025-09-10',
                'periode_id' => 1,
                'created_by' => 1,
                'is_verified' => 'Disetujui',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'UI/UX Design Challenge',
                'penyelenggara' => 'Google Developer Student Club',
                'tingkat' => 'Kota/Kabupaten',
                'bidang_keahlian_id' => 3,
                'persyaratan' => 'Tim max 3 orang',
                'jumlah_peserta' => 3,
                'link_registrasi' => 'https://uxchallenge.com',
                'tanggal_mulai' => '2025-08-15',
                'tanggal_selesai' => '2025-08-30',
                'periode_id' => 1,
                'created_by' => 2,
                'is_verified' => 'Disetujui',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Data Science Competition',
                'penyelenggara' => 'BPS',
                'tingkat' => 'Nasional',
                'bidang_keahlian_id' => 2,
                'persyaratan' => 'Mahasiswa S1/D4',
                'jumlah_peserta' => 2,
                'link_registrasi' => 'https://datasciencecomp.id',
                'tanggal_mulai' => '2025-10-01',
                'tanggal_selesai' => '2025-10-15',
                'periode_id' => 2,
                'created_by' => 3,
                'is_verified' => 'Disetujui',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'AI Innovation Fest',
                'penyelenggara' => 'AI Center Indonesia',
                'tingkat' => 'Internasional',
                'bidang_keahlian_id' => 7,
                'persyaratan' => 'Proposal dan video demo',
                'jumlah_peserta' => 3,
                'link_registrasi' => 'https://aiinnovationfest.org',
                'tanggal_mulai' => '2025-11-05',
                'tanggal_selesai' => '2025-11-20',
                'periode_id' => 2,
                'created_by' => 1,
                'is_verified' => 'Disetujui',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Cybersecurity War Games',
                'penyelenggara' => 'BSSN',
                'tingkat' => 'Nasional',
                'bidang_keahlian_id' => 5,
                'persyaratan' => 'Mahasiswa IT',
                'jumlah_peserta' => 2,
                'link_registrasi' => 'https://cyberwargames.id',
                'tanggal_mulai' => '2025-07-10',
                'tanggal_selesai' => '2025-07-15',
                'periode_id' => 1,
                'created_by' => 2,
                'is_verified' => 'Disetujui',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Cloud Innovation Challenge',
                'penyelenggara' => 'Amazon Web Services',
                'tingkat' => 'Internasional',
                'bidang_keahlian_id' => 6,
                'persyaratan' => 'Mahasiswa aktif, tim 3 orang',
                'jumlah_peserta' => 3,
                'link_registrasi' => 'https://awscloudchallenge.com',
                'tanggal_mulai' => '2025-12-01',
                'tanggal_selesai' => '2025-12-20',
                'periode_id' => 2,
                'created_by' => 3,
                'is_verified' => 'Ditolak',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'DevOps Automation Contest',
                'penyelenggara' => 'Docker Community',
                'tingkat' => 'Provinsi', // disesuaikan dari 'Regional'
                'bidang_keahlian_id' => 9,
                'persyaratan' => 'Menguasai CI/CD',
                'jumlah_peserta' => 2,
                'link_registrasi' => 'https://devopscontest.com',
                'tanggal_mulai' => '2025-01-10',
                'tanggal_selesai' => '2025-01-25',
                'periode_id' => 3,
                'created_by' => 1,
                'is_verified' => 'Ditolak',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Game Jam Indonesia',
                'penyelenggara' => 'Indie Game Dev ID',
                'tingkat' => 'Nasional',
                'bidang_keahlian_id' => 10,
                'persyaratan' => 'Mahasiswa semua jurusan',
                'jumlah_peserta' => 4,
                'link_registrasi' => 'https://gamejam.id',
                'tanggal_mulai' => '2025-02-01',
                'tanggal_selesai' => '2025-02-05',
                'periode_id' => 3,
                'created_by' => 2,
                'is_verified' => 'Ditolak',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mobile Dev Competition',
                'penyelenggara' => 'Dicoding',
                'tingkat' => 'Nasional',
                'bidang_keahlian_id' => 4,
                'persyaratan' => 'Membuat aplikasi Android/iOS',
                'jumlah_peserta' => 1,
                'link_registrasi' => 'https://mobiledevcomp.com',
                'tanggal_mulai' => '2025-03-10',
                'tanggal_selesai' => '2025-03-20',
                'periode_id' => 3,
                'created_by' => 3,
                'is_verified' => 'Ditolak',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Machine Learning Championship',
                'penyelenggara' => 'ID AI Forum',
                'tingkat' => 'Nasional',
                'bidang_keahlian_id' => 8,
                'persyaratan' => 'Submit model dan laporan',
                'jumlah_peserta' => 2,
                'link_registrasi' => 'https://mlchampionship.id',
                'tanggal_mulai' => '2025-04-05',
                'tanggal_selesai' => '2025-04-15',
                'periode_id' => 3,
                'created_by' => 1,
                'is_verified' => 'Ditolak',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

    }
}
